### ISSUE TITLE
Breakable Algorithm Block

### ISSUE THREAD

**Issue by Stumble** [Tedxz/xjtuthesis-x#1]
Since this commit 858dfd8ccc762c6274bafbe1f82b0a0a1893c810, writing decorated pseudo codes is in supported. However, the '/begin{algorithm} /end{algorithm}' block is float, so that if the pseudo codes are long enough (20 lines or so), LaTex would break the page and make a whole new page for pseudo codes. This way of dealing with long pseudo codes is not right according to the document from dean.

If we will stick to algorithmic package, I found a way to solve this problem. Someone called Werner proposed a solution of breakable algorithm block in this page:
http://tex.stackexchange.com/questions/33866/algorithm-tag-and-page-break

Here are his code:

```
\makeatletter
\newenvironment{breakablealgorithm}
  {% \begin{breakablealgorithm}
   \begin{center}
     \refstepcounter{algorithm}% New algorithm
     \hrule height.8pt depth0pt \kern2pt% \@fs@pre for \@fs@ruled
     \renewcommand{\caption}[2][\relax]{% Make a new \caption
       {\raggedright\textbf{\ALG@name~\thealgorithm} ##2\par}%
       \ifx\relax##1\relax % #1 is \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##2}%
       \else % #1 is not \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##1}%
       \fi
       \kern2pt\hrule\kern2pt
     }
  }{% \end{breakablealgorithm}
     \kern2pt\hrule\relax% \@fs@post for \@fs@ruled
   \end{center}
  }
\makeatother
```

Then use breakablealgorithm as the replacement of algorithm to wrap the algorithmic block.

example:

```
 \begin{breakablealgorithm}
    \caption{队列操作}
    \label{alg:queue}
    \begin{algorithmic}[1]
      \Procedure {queueUpdate}{$\bm{Q^{(1)}, Q^{(2)}, Q^{(3)}}$, $block$}
      \State $I am the code$
    \end{algorithmic}
  \end{breakablealgorithm}
```

**Comment by Tedxz** [comment]
Breakable algorithm environment has been added in commit 0e958ee5a065d57db5873d3beacf1ebf85ff49d6 and some bugs are fixed in commit 310e281ab27154f71c217c776c2e4d9570b48df9 and earlier ones. Thank you for your comment and solution!
