### ISSUE TITLE
prevent padding spaces between paragraphs

### ISSUE THREAD

**Issue by Stumble** [Tedxz/xjtuthesis-x#2]
Sometimes LaTex would add extra vertical spaces between paragraphs so that in the beginning of the next page, a new numbered section will begin at the top of the page. This 'feature' is wrong according to the official document: no extra spaces between paragraphs.

A simple way to solve it is to use: '\raggedbottom' command in style files. I suggest that to make it as the default setting and update the document.

**Comment by Tedxz** [comment]
This issue has been solved in commit af913c8983472704e9df83f44392abb6a9706e44, thank you for your comment and solution.
