### ISSUE TITLE
附录的二级标题和三级标题会重叠

### ISSUE THREAD

**Issue by sharuijinfriend** [Tedxz/xjtuthesis-x#7]
我在使用附录的时候遇到一个问题，附录的二级标题和三级标题排版有问题，会重叠在一起。
\xjtuappendixchapter{附录}
 \xjtuappendixsection{code}
 \xjtuappendixsubsection{主模块}
![image](https://user-images.githubusercontent.com/33866506/41232536-45f1c5e2-6db9-11e8-8488-19d617bc6959.png)
最后的显示就重叠在一起。不知道为什么会这样子

**Comment by Tedxz** [comment]
Merged @GenkunAbe 's PR.
